export const COPY = {
  comments: {
    title: 'Comments',
    placeholder: 'Add a comment…',
    replyPlaceholder: 'Write a reply…',
    hint: 'Enter to post · Shift+Enter for new line',
    post: 'Post',
    reply: 'Reply',
    posting: 'Posting…',
    cancel: 'Cancel',
    emoji: 'Emoji',
    like: 'Like',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    saving: 'Saving…',
    emptyTitle: 'No comments yet',
    emptyBody: 'Start the conversation — share your thoughts on this post.',
    loadMore: 'Load more comments',
    showReplies: (n) => `View ${n} ${n === 1 ? 'reply' : 'replies'}`,
    hideReplies: 'Hide replies',
    edited: 'Edited',
    deleteConfirm: 'Delete this comment?',
    sort: { latest: 'Latest', oldest: 'Oldest', top: 'Top' },
  },
};
