/** Shared demo password for all seeded accounts */
const DEMO_PASSWORD = process.env.SEED_DEMO_PASSWORD || 'Demo@12345';

const PHOTOS = {
  m1: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=400',
  m2: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400',
  m3: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=400',
  m4: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=400',
  m5: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=400',
  f1: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=400',
  f2: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=400',
  f3: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=400',
  f4: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=400',
  f5: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=400',
  t1: 'https://images.pexels.com/photos/1040882/pexels-photo-1040882.jpeg?auto=compress&cs=tinysrgb&w=400',
  t2: 'https://images.pexels.com/photos/3785079/pexels-photo-3785079.jpeg?auto=compress&cs=tinysrgb&w=400',
};

const students = [
  {
    email: 'demo.student01@rcpit.demo',
    first_name: 'Yash', last_name: 'Chaudhari', phone_number: '9876501001', photo: PHOTOS.m1,
    degree: 'B.Tech', branch: 'Computer Engineering', academic_batch: '2022-2026',
    year: 'Final Year', semester: '7', roll_number: 'RCPIT22CE001', division: 'A',
    admission_year: 2022, expected_graduation_year: 2026,
    headline: 'Full-stack developer · Open source contributor',
    bio: 'Final-year Computer Engineering student passionate about web systems, cloud-native apps, and campus tech communities.',
    location: 'Shirpur, Maharashtra',
    skills: [{ name: 'React', level: 8 }, { name: 'Node.js', level: 7 }, { name: 'PostgreSQL', level: 6 }],
    education: [{ institution_name: 'R.C. Patel Institute of Technology', degree: 'B.Tech', field_of_study: 'Computer Engineering', start_year: 2022, end_year: 2026, cgpa: '8.6' }],
    projects: [{ title: 'Campus Connect Portal', description: 'Student networking platform with real-time feeds and events.', technologies: ['React', 'Node.js'] }],
    social: { github: 'https://github.com/yashchaudhari', linkedin: 'https://linkedin.com/in/yashchaudhari-demo' },
  },
  {
    email: 'demo.student02@rcpit.demo',
    first_name: 'Priya', last_name: 'Patel', phone_number: '9876501002', photo: PHOTOS.f1,
    degree: 'B.Tech', branch: 'Information Technology', academic_batch: '2023-2027',
    year: 'TY', semester: '5', roll_number: 'RCPIT23IT014', division: 'B',
    admission_year: 2023, expected_graduation_year: 2027,
    headline: 'Cybersecurity enthusiast · CTF player',
    bio: 'Third-year IT student exploring network security, ethical hacking, and secure software design.',
    location: 'Dhule, Maharashtra',
    skills: [{ name: 'Python', level: 7 }, { name: 'Linux', level: 8 }, { name: 'Networking', level: 6 }],
    education: [{ institution_name: 'R.C. Patel Institute of Technology', degree: 'B.Tech', field_of_study: 'Information Technology', start_year: 2023, end_year: 2027, cgpa: '8.2' }],
    projects: [{ title: 'Network Scanner Tool', description: 'CLI utility for subnet discovery and port scanning in lab environments.', technologies: ['Python'] }],
    social: { github: 'https://github.com/priyapatel-demo', linkedin: 'https://linkedin.com/in/priyapatel-demo' },
  },
  {
    email: 'demo.student03@rcpit.demo',
    first_name: 'Rahul', last_name: 'Sharma', phone_number: '9876501003', photo: PHOTOS.m2,
    degree: 'B.Tech', branch: 'Mechanical Engineering', academic_batch: '2023-2027',
    year: 'TY', semester: '6', roll_number: 'RCPIT23ME008', division: 'A',
    admission_year: 2023, expected_graduation_year: 2027,
    headline: 'CAD designer · Robotics club lead',
    bio: 'Mechanical engineering student focused on design automation, robotics, and sustainable manufacturing.',
    location: 'Nashik, Maharashtra',
    skills: [{ name: 'AutoCAD', level: 8 }, { name: 'SolidWorks', level: 7 }, { name: 'MATLAB', level: 5 }],
    education: [{ institution_name: 'R.C. Patel Institute of Technology', degree: 'B.Tech', field_of_study: 'Mechanical Engineering', start_year: 2023, end_year: 2027, cgpa: '7.9' }],
    projects: [{ title: 'Automated Sorting Arm', description: 'Pick-and-place robotic arm prototype for industrial training lab.', technologies: ['Arduino', 'SolidWorks'] }],
    social: { linkedin: 'https://linkedin.com/in/rahulsharma-demo' },
  },
  {
    email: 'demo.student04@rcpit.demo',
    first_name: 'Ananya', last_name: 'Desai', phone_number: '9876501004', photo: PHOTOS.f2,
    degree: 'B.Tech', branch: 'Civil Engineering', academic_batch: '2024-2028',
    year: 'SY', semester: '4', roll_number: 'RCPIT24CE019', division: 'C',
    admission_year: 2024, expected_graduation_year: 2028,
    headline: 'Structural design · Green building advocate',
    bio: 'Second-year civil student interested in sustainable infrastructure and BIM workflows.',
    location: 'Jalgaon, Maharashtra',
    skills: [{ name: 'AutoCAD', level: 7 }, { name: 'STAAD Pro', level: 5 }, { name: 'Surveying', level: 6 }],
    education: [{ institution_name: 'R.C. Patel Institute of Technology', degree: 'B.Tech', field_of_study: 'Civil Engineering', start_year: 2024, end_year: 2028, cgpa: '8.0' }],
    projects: [{ title: 'Green Hostel Retrofit Study', description: 'Feasibility analysis for rainwater harvesting and solar rooftops.', technologies: ['Excel', 'AutoCAD'] }],
    social: { linkedin: 'https://linkedin.com/in/ananyadesai-demo' },
  },
  {
    email: 'demo.student05@rcpit.demo',
    first_name: 'Vikram', last_name: 'Singh', phone_number: '9876501005', photo: PHOTOS.m3,
    degree: 'B.Tech', branch: 'Electronics & Telecommunication', academic_batch: '2024-2028',
    year: 'SY', semester: '3', roll_number: 'RCPIT24ENT011', division: 'A',
    admission_year: 2024, expected_graduation_year: 2028,
    headline: 'Embedded systems · IoT hobbyist',
    bio: 'E&TC student building sensor networks and learning VLSI fundamentals.',
    location: 'Shirpur, Maharashtra',
    skills: [{ name: 'Embedded C', level: 7 }, { name: 'Arduino', level: 8 }, { name: 'PCB Design', level: 5 }],
    education: [{ institution_name: 'R.C. Patel Institute of Technology', degree: 'B.Tech', field_of_study: 'Electronics & Telecommunication', start_year: 2024, end_year: 2028, cgpa: '7.8' }],
    projects: [{ title: 'Smart Agriculture Monitor', description: 'LoRa-based soil moisture and weather telemetry for farms.', technologies: ['ESP32', 'LoRa'] }],
    social: { github: 'https://github.com/vikramsingh-demo' },
  },
  {
    email: 'demo.student06@rcpit.demo',
    first_name: 'Sneha', last_name: 'Kulkarni', phone_number: '9876501006', photo: PHOTOS.f3,
    degree: 'B.Tech', branch: 'Computer Engineering', academic_batch: '2024-2028',
    year: 'SY', semester: '4', roll_number: 'RCPIT24CE027', division: 'B',
    admission_year: 2024, expected_graduation_year: 2028,
    headline: 'UI/UX designer · Frontend developer',
    bio: 'Design-minded developer crafting accessible interfaces for campus and community apps.',
    location: 'Pune, Maharashtra',
    skills: [{ name: 'Figma', level: 9 }, { name: 'React', level: 7 }, { name: 'Tailwind CSS', level: 8 }],
    education: [{ institution_name: 'R.C. Patel Institute of Technology', degree: 'B.Tech', field_of_study: 'Computer Engineering', start_year: 2024, end_year: 2028, cgpa: '8.4' }],
    projects: [{ title: 'Design System for VH', description: 'Component library and tokens for Vidyalaya Hub UI.', technologies: ['Figma', 'React'] }],
    social: { github: 'https://github.com/snehakulkarni-demo', website: 'https://sneha-design.demo' },
  },
  {
    email: 'demo.student07@rcpit.demo',
    first_name: 'Arjun', last_name: 'Mehta', phone_number: '9876501007', photo: PHOTOS.m4,
    degree: 'B.Tech', branch: 'Electrical Engineering', academic_batch: '2025-2029',
    year: 'FY', semester: '2', roll_number: 'RCPIT25EE006', division: 'A',
    admission_year: 2025, expected_graduation_year: 2029,
    headline: 'Power systems · EV charging projects',
    bio: 'First-year electrical student exploring renewable energy integration and EV infrastructure.',
    location: 'Surat, Gujarat',
    skills: [{ name: 'MATLAB', level: 5 }, { name: 'Circuit Design', level: 6 }, { name: 'Python', level: 5 }],
    education: [{ institution_name: 'R.C. Patel Institute of Technology', degree: 'B.Tech', field_of_study: 'Electrical Engineering', start_year: 2025, end_year: 2029, cgpa: '7.5' }],
    projects: [{ title: 'Mini Solar Inverter', description: 'Lab-scale inverter prototype with MPPT simulation.', technologies: ['MATLAB', 'Simulink'] }],
    social: { linkedin: 'https://linkedin.com/in/arjunmehta-demo' },
  },
  {
    email: 'demo.student08@rcpit.demo',
    first_name: 'Isha', last_name: 'Joshi', phone_number: '9876501008', photo: PHOTOS.f4,
    degree: 'B.Tech', branch: 'Information Technology', academic_batch: '2025-2029',
    year: 'FY', semester: '1', roll_number: 'RCPIT25IT003', division: 'B',
    admission_year: 2025, expected_graduation_year: 2029,
    headline: 'Data science beginner · Python learner',
    bio: 'First-year IT student learning programming fundamentals and data visualization.',
    location: 'Ahmedabad, Gujarat',
    skills: [{ name: 'Python', level: 6 }, { name: 'Pandas', level: 5 }, { name: 'SQL', level: 4 }],
    education: [{ institution_name: 'R.C. Patel Institute of Technology', degree: 'B.Tech', field_of_study: 'Information Technology', start_year: 2025, end_year: 2029, cgpa: '8.1' }],
    projects: [{ title: 'Attendance Analytics Dashboard', description: 'Simple dashboard for class attendance trends.', technologies: ['Python', 'Streamlit'] }],
    social: { github: 'https://github.com/ishajoshi-demo' },
  },
  {
    email: 'demo.student09@rcpit.demo',
    first_name: 'Karan', last_name: 'Nair', phone_number: '9876501009', photo: PHOTOS.m5,
    degree: 'B.Tech', branch: 'Computer Engineering', academic_batch: '2022-2026',
    year: 'Final Year', semester: '8', roll_number: 'RCPIT22CE033', division: 'A',
    admission_year: 2022, expected_graduation_year: 2026,
    headline: 'ML engineer · Kaggle contributor',
    bio: 'Final-year student specializing in machine learning, NLP, and MLOps pipelines.',
    location: 'Mumbai, Maharashtra',
    skills: [{ name: 'Python', level: 9 }, { name: 'TensorFlow', level: 7 }, { name: 'Docker', level: 6 }],
    education: [{ institution_name: 'R.C. Patel Institute of Technology', degree: 'B.Tech', field_of_study: 'Computer Engineering', start_year: 2022, end_year: 2026, cgpa: '9.0' }],
    projects: [{ title: 'Campus Chatbot', description: 'RAG-based assistant for college FAQs and notices.', technologies: ['Python', 'LangChain'] }],
    social: { github: 'https://github.com/karannair-demo', linkedin: 'https://linkedin.com/in/karannair-demo' },
  },
  {
    email: 'demo.student10@rcpit.demo',
    first_name: 'Meera', last_name: 'Reddy', phone_number: '9876501010', photo: PHOTOS.f5,
    degree: 'B.Tech', branch: 'Mechanical Engineering', academic_batch: '2025-2029',
    year: 'FY', semester: '2', roll_number: 'RCPIT25ME012', division: 'C',
    admission_year: 2025, expected_graduation_year: 2029,
    headline: 'Thermodynamics · Formula Student team',
    bio: 'Mechanical student on the college Formula Student team, focused on vehicle dynamics.',
    location: 'Hyderabad, Telangana',
    skills: [{ name: 'SolidWorks', level: 6 }, { name: 'ANSYS', level: 5 }, { name: 'Team Management', level: 7 }],
    education: [{ institution_name: 'R.C. Patel Institute of Technology', degree: 'B.Tech', field_of_study: 'Mechanical Engineering', start_year: 2025, end_year: 2029, cgpa: '7.7' }],
    projects: [{ title: 'FSAE Brake System Design', description: 'Lightweight brake rotor and caliper mount analysis.', technologies: ['SolidWorks', 'ANSYS'] }],
    social: { linkedin: 'https://linkedin.com/in/meereddy-demo' },
  },
];

const alumni = [
  {
    email: 'demo.alumni01@rcpit.demo',
    first_name: 'Amit', last_name: 'Verma', phone_number: '9876502001', photo: PHOTOS.m2,
    degree: 'B.Tech', branch: 'Computer Engineering', admission_year: 2016, graduation_year: 2020,
    roll_number: 'RCPIT16CE045', company: 'TCS', position: 'Senior Software Engineer',
    headline: 'Building scalable backend systems at TCS',
    bio: 'RCPIT alumnus working on enterprise Java and cloud migration projects. Mentors juniors on placements.',
    location: 'Pune, Maharashtra',
    skills: [{ name: 'Java', level: 9 }, { name: 'Spring Boot', level: 8 }, { name: 'AWS', level: 7 }],
    education: [{ institution_name: 'R.C. Patel Institute of Technology', degree: 'B.Tech', field_of_study: 'Computer Engineering', start_year: 2016, end_year: 2020, cgpa: '8.7' }],
    experience: [{ title: 'Senior Software Engineer', company: 'TCS', start_year: 2022, is_current_role: true, description: 'Lead developer for banking modernization squad.' }, { title: 'Software Engineer', company: 'TCS', start_year: 2020, end_year: 2022, description: 'Full-stack development for internal tools.' }],
    social: { linkedin: 'https://linkedin.com/in/amitverma-demo', github: 'https://github.com/amitverma-demo' },
  },
  {
    email: 'demo.alumni02@rcpit.demo',
    first_name: 'Neha', last_name: 'Gupta', phone_number: '9876502002', photo: PHOTOS.f1,
    degree: 'B.Tech', branch: 'Information Technology', admission_year: 2017, graduation_year: 2021,
    roll_number: 'RCPIT17IT022', company: 'Infosys', position: 'Cloud Engineer',
    headline: 'Cloud engineer · AWS certified',
    bio: 'Alumni working on cloud infrastructure, DevOps pipelines, and cost optimization.',
    location: 'Bangalore, Karnataka',
    skills: [{ name: 'AWS', level: 9 }, { name: 'Terraform', level: 8 }, { name: 'Kubernetes', level: 7 }],
    education: [{ institution_name: 'R.C. Patel Institute of Technology', degree: 'B.Tech', field_of_study: 'Information Technology', start_year: 2017, end_year: 2021, cgpa: '8.5' }],
    experience: [{ title: 'Cloud Engineer', company: 'Infosys', start_year: 2021, is_current_role: true, description: 'Managed multi-account AWS landing zones.' }],
    social: { linkedin: 'https://linkedin.com/in/nehagupta-demo' },
  },
  {
    email: 'demo.alumni03@rcpit.demo',
    first_name: 'Rohan', last_name: 'Kapoor', phone_number: '9876502003', photo: PHOTOS.m3,
    degree: 'B.Tech', branch: 'Computer Engineering', admission_year: 2015, graduation_year: 2019,
    roll_number: 'RCPIT15CE018', company: 'Google', position: 'Product Manager',
    headline: 'PM at Google · Ex-startup founder',
    bio: 'Product leader focused on developer tools and education platforms.',
    location: 'Hyderabad, Telangana',
    skills: [{ name: 'Product Strategy', level: 9 }, { name: 'SQL', level: 7 }, { name: 'UX Research', level: 8 }],
    education: [{ institution_name: 'R.C. Patel Institute of Technology', degree: 'B.Tech', field_of_study: 'Computer Engineering', start_year: 2015, end_year: 2019, cgpa: '8.9' }],
    experience: [{ title: 'Product Manager', company: 'Google', start_year: 2022, is_current_role: true }, { title: 'Co-founder', company: 'EduSpark Labs', start_year: 2019, end_year: 2022 }],
    social: { linkedin: 'https://linkedin.com/in/rohankapoor-demo' },
  },
  {
    email: 'demo.alumni04@rcpit.demo',
    first_name: 'Pooja', last_name: 'Shah', phone_number: '9876502004', photo: PHOTOS.f2,
    degree: 'B.Tech', branch: 'Electronics & Telecommunication', admission_year: 2014, graduation_year: 2018,
    roll_number: 'RCPIT14ENT009', company: 'Qualcomm', position: 'Hardware Design Engineer',
    headline: 'SoC design · VLSI specialist',
    bio: 'Alumni designing low-power chipsets for mobile platforms.',
    location: 'San Diego, USA',
    skills: [{ name: 'Verilog', level: 9 }, { name: 'SystemVerilog', level: 8 }, { name: 'Timing Analysis', level: 8 }],
    education: [{ institution_name: 'R.C. Patel Institute of Technology', degree: 'B.Tech', field_of_study: 'Electronics & Telecommunication', start_year: 2014, end_year: 2018, cgpa: '8.3' }],
    experience: [{ title: 'Hardware Design Engineer', company: 'Qualcomm', start_year: 2018, is_current_role: true }],
    social: { linkedin: 'https://linkedin.com/in/poojashah-demo' },
  },
  {
    email: 'demo.alumni05@rcpit.demo',
    first_name: 'Sanjay', last_name: 'Iyer', phone_number: '9876502005', photo: PHOTOS.m4,
    degree: 'B.Tech', branch: 'Mechanical Engineering', admission_year: 2013, graduation_year: 2017,
    roll_number: 'RCPIT13ME031', company: 'L&T Construction', position: 'Project Manager',
    headline: 'Infrastructure PM · PMP certified',
    bio: 'Alumni managing large-scale civil infrastructure projects across western India.',
    location: 'Mumbai, Maharashtra',
    skills: [{ name: 'Project Management', level: 9 }, { name: 'Primavera', level: 8 }, { name: 'AutoCAD', level: 7 }],
    education: [{ institution_name: 'R.C. Patel Institute of Technology', degree: 'B.Tech', field_of_study: 'Mechanical Engineering', start_year: 2013, end_year: 2017, cgpa: '7.8' }],
    experience: [{ title: 'Project Manager', company: 'L&T Construction', start_year: 2020, is_current_role: true }, { title: 'Site Engineer', company: 'L&T Construction', start_year: 2017, end_year: 2020 }],
    social: { linkedin: 'https://linkedin.com/in/sanjayiyer-demo' },
  },
  {
    email: 'demo.alumni06@rcpit.demo',
    first_name: 'Divya', last_name: 'Rao', phone_number: '9876502006', photo: PHOTOS.f3,
    degree: 'B.Tech', branch: 'Computer Engineering', admission_year: 2018, graduation_year: 2022,
    roll_number: 'RCPIT18CE052', company: 'Microsoft', position: 'Data Analyst',
    headline: 'Data analyst · Power BI expert',
    bio: 'Turning product telemetry into actionable insights for enterprise SaaS teams.',
    location: 'Bangalore, Karnataka',
    skills: [{ name: 'SQL', level: 9 }, { name: 'Power BI', level: 9 }, { name: 'Python', level: 7 }],
    education: [{ institution_name: 'R.C. Patel Institute of Technology', degree: 'B.Tech', field_of_study: 'Computer Engineering', start_year: 2018, end_year: 2022, cgpa: '8.6' }],
    experience: [{ title: 'Data Analyst', company: 'Microsoft', start_year: 2022, is_current_role: true }],
    social: { linkedin: 'https://linkedin.com/in/divyarao-demo' },
  },
  {
    email: 'demo.alumni07@rcpit.demo',
    first_name: 'Manish', last_name: 'Thakur', phone_number: '9876502007', photo: PHOTOS.m5,
    degree: 'B.Tech', branch: 'Information Technology', admission_year: 2012, graduation_year: 2016,
    roll_number: 'RCPIT12IT007', company: 'Self-employed', position: 'Founder & CEO',
    headline: 'Entrepreneur · EdTech startup founder',
    bio: 'Founded an EdTech startup delivering vernacular coding courses to tier-2 cities.',
    location: 'Shirpur, Maharashtra',
    skills: [{ name: 'Business Development', level: 9 }, { name: 'React', level: 6 }, { name: 'Marketing', level: 8 }],
    education: [{ institution_name: 'R.C. Patel Institute of Technology', degree: 'B.Tech', field_of_study: 'Information Technology', start_year: 2012, end_year: 2016, cgpa: '7.6' }],
    experience: [{ title: 'Founder & CEO', company: 'CodeShala India', start_year: 2018, is_current_role: true }],
    social: { website: 'https://codeshala.demo', linkedin: 'https://linkedin.com/in/manishthakur-demo' },
  },
  {
    email: 'demo.alumni08@rcpit.demo',
    first_name: 'Kavita', last_name: 'Menon', phone_number: '9876502008', photo: PHOTOS.f4,
    degree: 'B.Tech', branch: 'Civil Engineering', admission_year: 2016, graduation_year: 2020,
    roll_number: 'RCPIT16CE028', company: 'AECOM', position: 'Structural Engineer',
    headline: 'Structural engineer · BIM workflows',
    bio: 'Designing resilient structures and leading BIM coordination on commercial projects.',
    location: 'Chennai, Tamil Nadu',
    skills: [{ name: 'STAAD Pro', level: 9 }, { name: 'Revit', level: 8 }, { name: 'ETABS', level: 7 }],
    education: [{ institution_name: 'R.C. Patel Institute of Technology', degree: 'B.Tech', field_of_study: 'Civil Engineering', start_year: 2016, end_year: 2020, cgpa: '8.1' }],
    experience: [{ title: 'Structural Engineer', company: 'AECOM', start_year: 2020, is_current_role: true }],
    social: { linkedin: 'https://linkedin.com/in/kavitamenon-demo' },
  },
  {
    email: 'demo.alumni09@rcpit.demo',
    first_name: 'Aditya', last_name: 'Malhotra', phone_number: '9876502009', photo: PHOTOS.m1,
    degree: 'B.Tech', branch: 'Computer Engineering', admission_year: 2019, graduation_year: 2023,
    roll_number: 'RCPIT19CE061', company: 'Amazon', position: 'SDE II',
    headline: 'SDE at Amazon · Distributed systems',
    bio: 'Building high-throughput services for retail fulfillment systems.',
    location: 'Seattle, USA',
    skills: [{ name: 'Java', level: 9 }, { name: 'DynamoDB', level: 8 }, { name: 'System Design', level: 8 }],
    education: [{ institution_name: 'R.C. Patel Institute of Technology', degree: 'B.Tech', field_of_study: 'Computer Engineering', start_year: 2019, end_year: 2023, cgpa: '9.1' }],
    experience: [{ title: 'SDE II', company: 'Amazon', start_year: 2023, is_current_role: true }],
    social: { github: 'https://github.com/adityamalhotra-demo', linkedin: 'https://linkedin.com/in/adityamalhotra-demo' },
  },
  {
    email: 'demo.alumni10@rcpit.demo',
    first_name: 'Shruti', last_name: 'Bansal', phone_number: '9876502010', photo: PHOTOS.f5,
    degree: 'B.Tech', branch: 'Electrical Engineering', admission_year: 2017, graduation_year: 2021,
    roll_number: 'RCPIT17EE015', company: 'Siemens', position: 'Automation Engineer',
    headline: 'Industrial automation · PLC programming',
    bio: 'Alumni designing PLC/SCADA solutions for manufacturing plants.',
    location: 'Noida, Uttar Pradesh',
    skills: [{ name: 'PLC Programming', level: 9 }, { name: 'SCADA', level: 8 }, { name: 'Industrial IoT', level: 7 }],
    education: [{ institution_name: 'R.C. Patel Institute of Technology', degree: 'B.Tech', field_of_study: 'Electrical Engineering', start_year: 2017, end_year: 2021, cgpa: '8.0' }],
    experience: [{ title: 'Automation Engineer', company: 'Siemens', start_year: 2021, is_current_role: true }],
    social: { linkedin: 'https://linkedin.com/in/shrutibansal-demo' },
  },
];

const teachers = [
  {
    email: 'demo.teacher01@rcpit.demo',
    first_name: 'Dr. Rajesh', last_name: 'Verma', phone_number: '9876503001', photo: PHOTOS.t1,
    department: 'Computer Engineering', designation: 'Head of Department',
    employee_id: 'RCPIT_F001', faculty_id: 'FAC-CE-001', qualification: 'Ph.D. Computer Science',
    specialization: 'Distributed Systems, Cloud Computing', joining_date: '2010-07-01',
    headline: 'HOD · Research in cloud-native architectures',
    bio: 'Professor and HOD with 15+ years teaching experience. Guides final-year projects and research publications.',
    location: 'Shirpur, Maharashtra',
    skills: [{ name: 'Cloud Computing', level: 10 }, { name: 'Research', level: 9 }, { name: 'Java', level: 8 }],
    education: [{ institution_name: 'IIT Bombay', degree: 'Ph.D.', field_of_study: 'Computer Science', start_year: 2006, end_year: 2010 }],
    experience: [{ title: 'Head of Department', company: 'R.C. Patel Institute of Technology', start_year: 2018, is_current_role: true }, { title: 'Associate Professor', company: 'R.C. Patel Institute of Technology', start_year: 2010, end_year: 2018 }],
    publications: [{ title: 'Scalable Microservices for Campus ERP', journal: 'IEEE Conference', year: 2022 }],
    social: { linkedin: 'https://linkedin.com/in/dr-rajeshverma-demo' },
  },
  {
    email: 'demo.teacher02@rcpit.demo',
    first_name: 'Prof. Sunita', last_name: 'Desai', phone_number: '9876503002', photo: PHOTOS.f2,
    department: 'Information Technology', designation: 'Associate Professor',
    employee_id: 'RCPIT_F002', qualification: 'M.Tech. Information Technology',
    specialization: 'Cybersecurity, Network Security', joining_date: '2012-06-15',
    headline: 'Cybersecurity faculty · CISSP',
    bio: 'Teaches network security, cryptography, and ethical hacking labs.',
    location: 'Shirpur, Maharashtra',
    skills: [{ name: 'Cybersecurity', level: 10 }, { name: 'Networking', level: 9 }, { name: 'Teaching', level: 9 }],
    education: [{ institution_name: 'VNIT Nagpur', degree: 'M.Tech.', field_of_study: 'Information Technology', start_year: 2010, end_year: 2012 }],
    experience: [{ title: 'Associate Professor', company: 'R.C. Patel Institute of Technology', start_year: 2017, is_current_role: true }],
    social: { linkedin: 'https://linkedin.com/in/prof-sunitadesai-demo' },
  },
  {
    email: 'demo.teacher03@rcpit.demo',
    first_name: 'Dr. Anil', last_name: 'Kulkarni', phone_number: '9876503003', photo: PHOTOS.t2,
    department: 'Mechanical Engineering', designation: 'Assistant Professor',
    employee_id: 'RCPIT_F003', qualification: 'Ph.D. Mechanical Engineering',
    specialization: 'Robotics, CAD/CAM', joining_date: '2015-08-01',
    headline: 'Robotics lab in-charge',
    bio: 'Mechanical faculty specializing in robotics, automation, and design engineering.',
    location: 'Shirpur, Maharashtra',
    skills: [{ name: 'Robotics', level: 9 }, { name: 'CAD/CAM', level: 9 }, { name: 'ANSYS', level: 8 }],
    education: [{ institution_name: 'COEP Pune', degree: 'Ph.D.', field_of_study: 'Mechanical Engineering', start_year: 2011, end_year: 2015 }],
    experience: [{ title: 'Assistant Professor', company: 'R.C. Patel Institute of Technology', start_year: 2015, is_current_role: true }],
    social: { linkedin: 'https://linkedin.com/in/dr-anilkulkarni-demo' },
  },
  {
    email: 'demo.teacher04@rcpit.demo',
    first_name: 'Prof. Meena', last_name: 'Joshi', phone_number: '9876503004', photo: PHOTOS.f3,
    department: 'Civil Engineering', designation: 'Assistant Professor',
    employee_id: 'RCPIT_F004', qualification: 'M.E. Structural Engineering',
    specialization: 'Structural Analysis, Green Buildings', joining_date: '2016-07-10',
    headline: 'Structural engineering · Green building consultant',
    bio: 'Civil faculty focused on structural design, surveying, and sustainable construction.',
    location: 'Shirpur, Maharashtra',
    skills: [{ name: 'Structural Engineering', level: 9 }, { name: 'STAAD Pro', level: 8 }, { name: 'Green Buildings', level: 7 }],
    education: [{ institution_name: 'SPPU Pune', degree: 'M.E.', field_of_study: 'Structural Engineering', start_year: 2014, end_year: 2016 }],
    experience: [{ title: 'Assistant Professor', company: 'R.C. Patel Institute of Technology', start_year: 2016, is_current_role: true }],
    social: { linkedin: 'https://linkedin.com/in/prof-meenajoshi-demo' },
  },
  {
    email: 'demo.teacher05@rcpit.demo',
    first_name: 'Dr. Vikram', last_name: 'Patil', phone_number: '9876503005', photo: PHOTOS.m3,
    department: 'Electronics & Telecommunication', designation: 'Associate Professor',
    employee_id: 'RCPIT_F005', qualification: 'Ph.D. Electronics Engineering',
    specialization: 'VLSI Design, Embedded Systems', joining_date: '2011-07-01',
    headline: 'VLSI & embedded systems researcher',
    bio: 'E&TC faculty guiding VLSI and embedded systems projects with industry collaborations.',
    location: 'Shirpur, Maharashtra',
    skills: [{ name: 'VLSI', level: 10 }, { name: 'Embedded Systems', level: 9 }, { name: 'Verilog', level: 9 }],
    education: [{ institution_name: 'IIT Delhi', degree: 'Ph.D.', field_of_study: 'Electronics Engineering', start_year: 2007, end_year: 2011 }],
    experience: [{ title: 'Associate Professor', company: 'R.C. Patel Institute of Technology', start_year: 2014, is_current_role: true }],
    publications: [{ title: 'Low-Power VLSI Design Techniques', journal: 'IET Journal', year: 2020 }],
    social: { linkedin: 'https://linkedin.com/in/dr-vikrampatil-demo' },
  },
  {
    email: 'demo.teacher06@rcpit.demo',
    first_name: 'Prof. Ravi', last_name: 'Sharma', phone_number: '9876503006', photo: PHOTOS.m4,
    department: 'Electrical Engineering', designation: 'Lecturer',
    employee_id: 'RCPIT_F006', qualification: 'M.Tech. Power Systems',
    specialization: 'Power Systems, Renewable Energy', joining_date: '2018-06-20',
    headline: 'Power systems lecturer · Solar energy projects',
    bio: 'Electrical faculty teaching power systems, machines, and renewable energy labs.',
    location: 'Shirpur, Maharashtra',
    skills: [{ name: 'Power Systems', level: 9 }, { name: 'Renewable Energy', level: 8 }, { name: 'MATLAB', level: 7 }],
    education: [{ institution_name: 'NIT Surat', degree: 'M.Tech.', field_of_study: 'Power Systems', start_year: 2016, end_year: 2018 }],
    experience: [{ title: 'Lecturer', company: 'R.C. Patel Institute of Technology', start_year: 2018, is_current_role: true }],
    social: { linkedin: 'https://linkedin.com/in/prof-ravisharma-demo' },
  },
  {
    email: 'demo.teacher07@rcpit.demo',
    first_name: 'Dr. Poonam', last_name: 'Gupta', phone_number: '9876503007', photo: PHOTOS.f1,
    department: 'Computer Engineering', designation: 'Assistant Professor',
    employee_id: 'RCPIT_F007', qualification: 'Ph.D. Machine Learning',
    specialization: 'Machine Learning, Data Science', joining_date: '2019-07-01',
    headline: 'ML faculty · AI research group lead',
    bio: 'Teaches AI/ML courses and supervises research in NLP and computer vision.',
    location: 'Shirpur, Maharashtra',
    skills: [{ name: 'Machine Learning', level: 10 }, { name: 'Python', level: 9 }, { name: 'Deep Learning', level: 9 }],
    education: [{ institution_name: 'IISc Bangalore', degree: 'Ph.D.', field_of_study: 'Machine Learning', start_year: 2014, end_year: 2019 }],
    experience: [{ title: 'Assistant Professor', company: 'R.C. Patel Institute of Technology', start_year: 2019, is_current_role: true }],
    publications: [{ title: 'Transfer Learning for Low-Resource Languages', journal: 'ACL Workshop', year: 2023 }],
    social: { linkedin: 'https://linkedin.com/in/dr-poonamgupta-demo' },
  },
  {
    email: 'demo.teacher08@rcpit.demo',
    first_name: 'Prof. Sandeep', last_name: 'Rao', phone_number: '9876503008', photo: PHOTOS.m5,
    department: 'Information Technology', designation: 'Lecturer',
    employee_id: 'RCPIT_F008', qualification: 'M.Tech. Software Engineering',
    specialization: 'Web Technologies, Software Engineering', joining_date: '2020-08-01',
    headline: 'Full-stack mentor · Placement trainer',
    bio: 'IT faculty helping students with full-stack projects and placement preparation.',
    location: 'Shirpur, Maharashtra',
    skills: [{ name: 'React', level: 9 }, { name: 'Node.js', level: 8 }, { name: 'Software Engineering', level: 8 }],
    education: [{ institution_name: 'PICT Pune', degree: 'M.Tech.', field_of_study: 'Software Engineering', start_year: 2018, end_year: 2020 }],
    experience: [{ title: 'Lecturer', company: 'R.C. Patel Institute of Technology', start_year: 2020, is_current_role: true }],
    social: { github: 'https://github.com/prof-sandeeprao-demo', linkedin: 'https://linkedin.com/in/prof-sandeeprao-demo' },
  },
  {
    email: 'demo.teacher09@rcpit.demo',
    first_name: 'Dr. Nisha', last_name: 'Iyer', phone_number: '9876503009', photo: PHOTOS.f4,
    department: 'Mechanical Engineering', designation: 'Associate Professor',
    employee_id: 'RCPIT_F009', qualification: 'Ph.D. Thermal Engineering',
    specialization: 'Thermodynamics, Heat Transfer', joining_date: '2013-07-01',
    headline: 'Thermal sciences · Energy systems',
    bio: 'Mechanical faculty researching thermal systems and energy efficiency in industrial processes.',
    location: 'Shirpur, Maharashtra',
    skills: [{ name: 'Thermodynamics', level: 10 }, { name: 'CFD', level: 8 }, { name: 'Research', level: 9 }],
    education: [{ institution_name: 'IIT Madras', degree: 'Ph.D.', field_of_study: 'Thermal Engineering', start_year: 2009, end_year: 2013 }],
    experience: [{ title: 'Associate Professor', company: 'R.C. Patel Institute of Technology', start_year: 2016, is_current_role: true }],
    social: { linkedin: 'https://linkedin.com/in/dr-nishaiyer-demo' },
  },
  {
    email: 'demo.teacher10@rcpit.demo',
    first_name: 'Prof. Harish', last_name: 'Nair', phone_number: '9876503010', photo: PHOTOS.t1,
    department: 'Civil Engineering', designation: 'Lecturer',
    employee_id: 'RCPIT_F010', qualification: 'M.E. Transportation Engineering',
    specialization: 'Transportation Engineering, Surveying', joining_date: '2021-07-01',
    headline: 'Transportation engineering · Survey camp coordinator',
    bio: 'Civil faculty coordinating survey camps and teaching transportation planning.',
    location: 'Shirpur, Maharashtra',
    skills: [{ name: 'Transportation Engineering', level: 8 }, { name: 'Surveying', level: 9 }, { name: 'AutoCAD', level: 7 }],
    education: [{ institution_name: 'VNIT Nagpur', degree: 'M.E.', field_of_study: 'Transportation Engineering', start_year: 2019, end_year: 2021 }],
    experience: [{ title: 'Lecturer', company: 'R.C. Patel Institute of Technology', start_year: 2021, is_current_role: true }],
    social: { linkedin: 'https://linkedin.com/in/prof-harishnair-demo' },
  },
];

module.exports = {
  DEMO_PASSWORD,
  students,
  alumni,
  teachers,
};
